---

codecov:
  notify:
    after_n_builds: 1  # The number of test matrix+lint jobs uploading coverage
    wait_for_ci: false

  require_ci_to_pass: false

comment:
  require_changes: true

coverage:
  range: 97.87..100
  status:
    project:
      default:
        target: 100%
      lib:
        paths:
        - multidict/**/*.py
        target: 94.05%
      tests:
        paths:
        - tests/
        target: 100%
      typing-stubs:
        paths:
        - >-
          **/*.pyi
        target: 100%

...
